# .readthedocs.yaml
# Read-the-Docs configuration file
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
   configuration: docs/conf.py

python:
  install:
    - requirements: ./requirements_dev.txt
    - method: pip
      path: .
    - method: setuptools
      path: .
