# Taken from https://github.com/mclegrand/scikit-network/blob/master/.github/workflows/python-package.yml

name: CI Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install codecov flake8
        python -m pip install -r requirements_dev.txt
        python setup.py develop
    - name: Test with pytest
      run: |
        py.test --doctest-modules --cov-report=xml --cov=sknetwork
    - name: Codecov
      run: |
        codecov
