# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_PLATFORM: auto
          CIBW_ARCHS: auto64
          CIBW_SKIP: cp*-musllinux*
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: "pip install -r requirements_dev.txt && pip install ."
          CIBW_BEFORE_BUILD_MACOS: "pip install -r requirements_dev.txt && pip install ."
          CIBW_BUILD: cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v3
          name: Install Python
          with:
            python-version: '3.9'

        - name: Build sdist
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements_dev.txt
            python setup.py sdist

        - uses: actions/upload-artifact@v3
          with:
            path: dist/*.tar.gz

  upload_pypi:
      needs: [ build_wheels, build_sdist ]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/download-artifact@v3
            with:
              name: artifact
              path: dist

          - uses: pypa/gh-action-pypi-publish@v1.4.2
            with:
              user: __token__
              password: ${{ secrets.TWINE_PASSWORD }}
